config/routes.rb
Rails.application.routes.draw do

  resources :products
  
  root 'products#index'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  monetize :price_cents, :allow_nil => false,
    :numericality => {
      :greater_than_or_equal_to => 0,
      :less_than_or_equal_to => 100000
    }

  validates :name, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 1000 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :all_products, only: [:index, :create]

  # GET /products
  # GET /products.json
  def index
    @product = Product.new
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price_cents)
    end

    def all_products
      @products = Product.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8" 
      meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" 
        meta content="width=device-width, initial-scale=1.0" name="viewport" 
          title= content_for?(:title) ? yield(:title) : "Bom"
          = csrf_meta_tags
          /! Le HTML5 shim, for IE6-8 support of HTML elements
          /![if lt IE 9]
            | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script
          = stylesheet_link_tag "application", :media => "all"
          /! For third-generation iPad with high-resolution Retina display:
          /! Size should be 144 x 144 pixels
          = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          /! For iPhone with high-resolution Retina display:
          /! Size should be 114 x 114 pixels
          = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          /! For first- and second-generation iPad:
          /! Size should be 72 x 72 pixels
          = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          /! Size should be 57 x 57 pixels
          = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          /! For all other devices
          /! Size should be 32 x 32 pixels
          = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
          = javascript_include_tag "application"
  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button" 
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#"  Bom
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to "Home", "/"
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Main", "/"
          /! /.well
        /! /span
      /! /row
      br
        br
          footer
            p &copy; Company 2014
    /! /container

app/views/products/_form.html.slim
.form_div
  = form_for @product, :html => { :class => "form-horizontal product" } do |f|
    - if @product.errors.any?
      #error_expl.panel.panel-danger
        .panel-heading
          h3.panel-title
            = pluralize(@product.errors.count, "error")
            | prohibited this product from being saved:
        .panel-body
          ul
            - @product.errors.full_messages.each do |msg|
              li= msg
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name, :class => 'form-control'
      = error_span(@product[:name])
    .control-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_field :description, :class => 'form-control'
      = error_span(@product[:description])
    .control-group
      = f.label :price, :class => 'control-label'
      | &nbsp;(in cents)
      .controls
        = f.number_field :price_cents, :class => 'form-control'
      = error_span(@product[:price_cents])
    br
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn btn-default cancel'

app/views/products/edit.html.slim
- model_class = Product
.page-header
  h1= t '.title', :default => [:'helpers.titles.edit', 'Edit % model '], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/products/index.html.slim
- model_class = Product
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:price)
      th= t '.actions', :default => t("helpers.actions")
  tbody
    - @products.each do |product|
      tr
        td= link_to product.id, product_path(product)
        td= product.name
        td= product.description
        td= humanized_money_with_symbol product.price_cents
        td
          = link_to t('.edit', :default => t("helpers.links.edit")),
            edit_product_path(product), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
h2 New product
= render :partial => 'form' 

app/views/products/show.html.slim
- model_class = Product
.page-header
  h1= t '.title', :default => model_class.model_name.human.titleize
dl.dl-horizontal
  dt
    strong
      = model_class.human_attribute_name(:name)
      | :
  dd= @product.name
  dt
    strong
      = model_class.human_attribute_name(:description)
      | :
  dd= @product.description
  dt
    strong
      = model_class.human_attribute_name(:price_cents)
      | :
  dd= humanized_money_with_symbol @product.price_cents
= link_to t('.back', :default => t("helpers.links.back")),products_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")),edit_product_path(@product), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")),product_path(@product), :method => 'delete',:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'